# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


yoga_categories = [
    YogaCategory.create!(name: 'Hatha', short_name: 'hatha', description: 'The Sanskrit term "hatha" is an umbrella term for all physical postures of yoga. In the West, hatha yoga simply refers to all the other styles of yoga (Ashtanga, Iyengar, etc.) that are grounded in a physical practice. However, there are other branches of yoga such as kriya, raja, and karma yoga that are separate from the physical-based yoga practice. The physical-based yoga is the most popular and has numerous styles. Hatha yoga classes are best for beginners since they are usually paced slower than other yoga styles. Hatha classes today are a classic approach to breathing and exercises. If you are brand-new to yoga, hatha yoga is a great entry point to the practice.'),
    YogaCategory.create!(name: 'Iyengar', short_name: 'iyengar', description: 'Iyengar yoga was founded by B.K.S. Iyengar and focuses on alignment as well as detailed and precise movements. In an Iyengar class, students perform a variety of postures while controlling the breath. Generally, poses are held for a long time while adjusting the minutiae of the pose. Iyengar relies heavily on props to help students perfect their form and go deeper into poses in a safe manner. Although you won’t jump around, you will definitely get a workout and feel incredibly open and relaxed after an Iyengar class. This style is really great for people with injuries who need to work slowly and methodically.'),
    YogaCategory.create!(name: 'Kundalini', short_name: 'kundalini', description: 'Kundalini yoga practice is equal parts spiritual and physical. This style is all about releasing the kundalini energy in your body said to be trapped, or coiled, in the lower spine. These classes really work your core and breathing with fast-moving, invigorating postures and breath exercises. These classes are pretty intense and can involve chanting, mantra, and meditation.'),
    YogaCategory.create!(name: 'Ashtanga', short_name: 'ashtanga', description: 'In Sanskrit Ashtanga is translated as "Eight Limb path." Ashtanga yoga involves a very physically demanding sequence of postures, so this style of yoga is definitely not for the beginner. It takes an experienced yogi to really love it. Ashtanga starts with five sun salutation A\'s and five sun salutation B\'s and then moves into a series of standing and floor postures. In Mysore, India, people gather to practice this form of yoga together at their own pace—if you see Mysore-led Ashtanga, it\'s expected of you to know the series. Vinyasa yoga stems from Ashtanga as the flowing style linking breath to movement.'),
    YogaCategory.create!(name: 'Vinyasa', short_name: 'vinyasa', description: 'Vinyasa means "to place in a special way" and in this case yoga postures. Vinyasa is the most athletic yoga style. Vinyasa was adapted from Ashtanga yoga in the 1980s. In Vinyasa classes, the movement is coordinated with your breath and movement to flow from one pose to another. Many types of yoga can also be considered Vinyasa flows such as Ashtanga, power yoga, and prana. Vinyasa styles can vary depending on the teacher, and there can be many different types of poses in different sequences. I personally teach an alignment-based style of vinyasa and choreograph new flows every time, but I also like to hold some of the poses a bit longer after warming up.'),
    YogaCategory.create!(name: 'Bikram', short_name: 'bikram', description: 'If you are looking to sweat in yoga, this is the style for you. Bikram yoga is named after Bikram Choudhury and features a sequence of set poses in a sauna-like room—typically set to 105 degrees and 40 percent humidity. The sequence includes a series of 26 basic postures, with each one performed twice.'),
    YogaCategory.create!(name: 'Yin', short_name: 'yin', description: 'Yin yoga is a slow-paced style of yoga with seated postures that are held for longer periods of time. Yin is a great class for beginners, as postures can be held from 45 seconds to two minutes. Yin can also be a meditative yoga practice that helps you find inner peace. The classes are relaxed, as you\'re supposed to let gravity do most of the work.'),
    YogaCategory.create!(name: 'Restorative', short_name: 'restorative', description: 'Restorative yoga focuses on winding down after a long day and relaxing your mind. At its core, this style focuses on body relaxation. You spend more time in fewer postures throughout the class. Many of the poses are modified to be easier and more relaxing. Like Iyengar, many props are used and are placed just right such as blankets, bolsters, and eye pillows. All of the props are there to help you sink deeper into relaxation. Restorative yoga also helps to cleanse and free your mind.'),
    YogaCategory.create!(name: 'Prenatal', short_name: 'prenatal', description: 'Prenatal yoga is carefully adapted for "moms to be" and is tailored to women in all trimesters. Many have said that prenatal is one of the best types of exercise for expectant moms because of the pelvic floor work, focus on breathing, and bonding with the growing baby; prenatal yoga also helps mothers prepare for labor and delivery. I also practiced my own form of prenatal yoga during both of my pregnancies.'),
    YogaCategory.create!(name: 'Anusara', short_name: 'anusara', description: 'Anusara is a modern-day version of hatha yoga, most similar to vinyasa in that it that focuses on alignment but with more focus on the mind-body-heart connection and different verbiage. Anusara focuses on spirals and how each body part should be moving. Anusara is also known for its emphasis on heart opening. Expect to often stop in class and gather around a student as the instructor breaks down a pose.'),
    YogaCategory.create!(name: 'Jivamukti', short_name: 'jivamukti', description: 'Jivamukti was founded in 1984 by Sharon Ganon and David Life. Jivamukti is mainly vinyasa flow-style classes infused with Hindu spiritual teachings. A series of chants usually open the beginning of class followed up by a series of poses that align with the five tenets of Jivamukti yoga and philosophy. At its core, this style emphasizes connection to Earth as a living being, so most Jivamukti devotees follow their vegetarian philosophy.'),
]

yoga_poses_list = JSON.parse(File.read(File.join(Rails.root, "/app/assets/seed/yoga_poses.json")))

yoga_poses_list['yoga_poses'].each do |pose|
  YogaPose.create!(pose.to_h)
end